# Conda environment for cypari2 development on Windows
# (using mingw-w64 toolchain)
#
# Usage:
#   mamba/conda env create -f environment-win.yml
#   conda activate cypari2-dev
#   pip install -e . --no-build-isolation
name: cypari2-dev
channels:
  - conda-forge

dependencies:
  # Build backend and build tools
  - python>=3.9
  - pari
  - cython>=3.0
  - cysignals>=1.11.3
  - meson-python>=0.18
  - gcc_win-64
  - m2w64-sysroot_win-64
  # For docs
  - sphinx
